const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.VGD_PLAYWRIGHT_MODULE || 'playwright');
const assert=(value,message)=>{if(!value)throw Error(message)};
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  const page=await browser.newPage({viewport:{width:960,height:760}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{window.calls=[];window.sketchup=new Proxy({}, {get:(_,name)=>(...args)=>window.calls.push({name,args})})});
  await page.goto(pathToFileURL(path.resolve(__dirname,'../runtime/vgd_bim_lite/html/index.html')).href);
  assert(await page.locator('#nav').evaluate(el=>Math.round(el.getBoundingClientRect().width)===190)&&await page.locator('.nav-copy').first().isVisible(),'Expanded navigation labels or width missing');
  await page.setViewportSize({width:600,height:800});
  assert(await page.locator('#nav').evaluate(el=>Math.round(el.getBoundingClientRect().width)===58)&&await page.locator('.nav-copy').first().isHidden(),'Compact navigation did not collapse to icon rail');
  assert(await page.locator('#nav .nav-item').first().evaluate(el=>!!el.title&&getComputedStyle(el.querySelector('svg')).display!=='none'),'Compact icon navigation has no tooltip or icon');
  await page.setViewportSize({width:960,height:760});
  assert(await page.locator('body').evaluate(el=>el.classList.contains('dark')),'First launch did not default to VGD dark theme');
  await page.click('#theme');
  assert(await page.locator('body').evaluate(el=>el.classList.contains('light'))&&await page.evaluate(()=>localStorage.getItem('VGD_BIM_theme'))==='light','Light theme preference was not applied and saved');
  assert((await page.locator('#brand-logo').getAttribute('src')).includes('vgd_primary_light.svg'),'Light theme brand logo did not update');
  await page.click('#theme');
  assert(await page.locator('body').evaluate(el=>el.classList.contains('dark'))&&await page.evaluate(()=>localStorage.getItem('VGD_BIM_theme'))==='dark','Dark theme toggle did not restore and save preference');
  const config={mode:'information',version:'0.1.2-alpha',categories:['furniture','electrical','finish'],units:['pcs','set','m2'],methods:['count','assembly','area'],presets:JSON.parse(fs.readFileSync(path.resolve(__dirname,'../runtime/vgd_bim_lite/config/presets.json'),'utf8')),locale:JSON.parse(fs.readFileSync(path.resolve(__dirname,'../runtime/vgd_bim_lite/config/vi.json'),'utf8'))};
  const receive=async(event,data)=>page.evaluate(([e,d])=>window.VGD.receive(e,d),[event,data]);
  await receive('config',config);
  await receive('information',{count:10,fields:{category:null,item_type:'socket',description:null,unit:'pcs',quantity_method:'count',include_boq:true},objects:[{entity_type:'Component',source:'RAW',instance_name:'<img src=x onerror="window.injected=true">',definition_name:'O_CAM_DOI',tag:'ELEC',material:'',dimensions:{width:120,depth:30,height:80},status:'UNCLASSIFIED',locked:false}]});
  assert(await page.locator('#content img').count()===0,'Unsafe entity name inserted as HTML');
  assert(await page.locator('#field-category').isDisabled(),'Mixed field automatically writable');
  await page.check('#update-zone');await page.fill('#field-zone','Phòng ngủ chính');await page.getByRole('button',{name:'Áp dụng thông tin',exact:true}).click();
  let last=await page.evaluate(()=>window.calls.at(-1));
  assert(last.name==='apply' && JSON.stringify(JSON.parse(last.args[0]))==='{"zone":"Phòng ngủ chính"}','Multi-edit overwrote unselected fields');
  await page.locator('main select').first().selectOption('3');
  assert(await page.locator('#field-category').inputValue()==='electrical'&&await page.locator('#field-item_type').inputValue()==='Ổ cắm'&&await page.locator('#update-description').isChecked()===false,'Preset translation or field scope wrong');
  await page.getByRole('button',{name:'Áp dụng thông tin',exact:true}).click();last=await page.evaluate(()=>window.calls.at(-1));assert(JSON.parse(last.args[0]).item_type==='socket','Vietnamese item label written into canonical schema');
  await page.selectOption('#field-include_boq','');const beforeBoolean=await page.evaluate(()=>window.calls.length);await page.getByRole('button',{name:'Áp dụng thông tin',exact:true}).click();assert(await page.evaluate(()=>window.calls.length)===beforeBoolean && (await page.locator('#message').innerText()).includes('Có hoặc Không'),'Blank boolean silently wrote false');
  await receive('config',{...config,mode:'mapping'});
  const row={index:0,source_type:'definition_name',source_value:'O_CAM_DOI',kind:'object',instances:28,eligible:28,protected:0,suggestion:{data:{category:'electrical',item_type:'socket',unit:'pcs',quantity_method:'count'},confidence:'HIGH',source:'HEURISTIC'}};
  await receive('mapping',[row]);await page.getByRole('button',{name:'Chỉnh thông tin'}).click();
  await page.check('#update-description');await page.fill('#field-description','Ổ cắm đôi');await page.getByRole('button',{name:'Xem trước chuyển đổi',exact:true}).click();
  last=await page.evaluate(()=>window.calls.at(-1));assert(last.name==='preview_convert'&&JSON.parse(last.args[0]).data.description==='Ổ cắm đôi','Preview did not preserve mapping values');
  const before=await page.evaluate(()=>window.calls.length);
  await receive('preview',{objects:28,occurrences:28,skipped:0,data:row.suggestion.data,rule:false,shared:false});assert(await page.locator('#preview').isVisible(),'Preview missing');
  await page.click('#cancel-preview');assert(await page.evaluate(()=>window.calls.length)===before,'Cancel preview wrote attributes');
  await receive('preview',{objects:28,occurrences:28,skipped:0,data:row.suggestion.data,rule:false,shared:true});await page.click('#confirm-preview');
  last=await page.evaluate(()=>window.calls.at(-1));assert(last.name==='confirm_convert','Convert confirmation missing');
  await receive('config',{...config,mode:'validate_model'});await receive('validation',[{index:7,status:'ERROR',instance_name:'Ổ cắm đôi',issues:[{severity:'ERROR',message:'Đếm số lượng cần đơn vị cái / bộ / lô'}]}]);await page.locator('tr.clickable').click();
  last=await page.evaluate(()=>window.calls.at(-1));assert(last.name==='select_entity'&&last.args[0]===7,'Validation selection targets wrong index');
  await receive('config',{...config,mode:'rules'});await receive('rules',[]);await page.getByText('Nâng cao · Chỉnh dữ liệu kỹ thuật',{exact:true}).click();await page.fill('#rules-json','INVALID');await page.getByRole('button',{name:'Lưu dữ liệu kỹ thuật'}).click();assert((await page.locator('#message').innerText()).includes('không đúng định dạng'),'Invalid rules JSON accepted');
  await page.getByRole('button',{name:'Thêm quy tắc',exact:true}).click();await page.fill('#rule-source-value','O_CAM_DOI');await page.selectOption('#preset','3');await page.getByRole('button',{name:'Lưu quy tắc',exact:true}).click();last=await page.evaluate(()=>window.calls.at(-1));assert(last.name==='save_rule'&&JSON.parse(last.args[0]).data.item_type==='socket','Friendly rule editor did not save canonical data');
  await page.locator('[data-mode="export"]').click();last=await page.evaluate(()=>window.calls.at(-1));assert(last.name==='open_panel'&&last.args[0]==='export','Export navigation missing');
  await receive('config',{...config,mode:'export'});assert(await page.locator('.export-item').count()===0,'Stale export enabled before scan complete');await receive('export',{objects:28,faces:42});assert(await page.locator('.export-item').count()===4,'Report options missing');await page.getByRole('button',{name:'Xuất CSV · Danh mục đối tượng',exact:true}).click();last=await page.evaluate(()=>window.calls.at(-1));assert(last.name==='export_report'&&last.args[0]==='bim','Wrong export report');
  await receive('config',{...config,mode:'information'});await receive('information',{count:0,fields:{},objects:[]});assert(await page.getByRole('button',{name:'Áp dụng thông tin',exact:true}).isDisabled(),'Empty selection can apply');
  await receive('information',{count:10,fields:{category:'electrical',item_type:'socket',description:'Ổ cắm đôi',unit:'pcs',quantity_method:'count',zone:'MASTER',include_boq:true},objects:[]});
  const output=path.resolve(__dirname,'../outputs');fs.mkdirSync(output,{recursive:true});await page.screenshot({path:path.join(output,'information_light.png'),fullPage:true});
  assert(await page.locator('body').evaluate(el=>el.classList.contains('dark')),'Theme preference did not remain dark');await page.screenshot({path:path.join(output,'information_dark.png'),fullPage:true});await page.click('#theme');assert(await page.locator('body').evaluate(el=>el.classList.contains('light')),'Theme switch missing');await page.screenshot({path:path.join(output,'information_light.png'),fullPage:true});
  await page.setViewportSize({width:600,height:800});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Compact layout overflows');
  const applyBox=await page.getByRole('button',{name:'Áp dụng thông tin',exact:true}).boundingBox();assert(applyBox && applyBox.y+applyBox.height<=800,`Primary apply action below visible viewport: ${JSON.stringify(applyBox)}`);
  assert(errors.length===0,errors.join('\n'));
  await page.goto(pathToFileURL(path.resolve(__dirname,'ui_preview.html')).href);
  await page.screenshot({path:path.join(output,'ui_preview_narrow.png'),fullPage:true});
  await page.setViewportSize({width:960,height:760});
  await page.screenshot({path:path.join(output,'ui_preview_wide.png'),fullPage:true});
  console.log('PASS: Vietnamese labels and canonical schema, multi-edit, preview/convert, validation, friendly rule editor, export navigation/options, theme, compact layout');
 }finally{await browser.close()}
})().catch(error=>{console.error(error);process.exitCode=1});
