const fs=require('fs');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{
 const defaults=JSON.parse(fs.readFileSync('cabinet_dev/defaults.json'));
 let html=fs.readFileSync('cabinet_work/VGD_Cabinet/VGD_Cabinet_UI.html','utf8');
 for(const [key,data] of [['presets_json',{}],['default_json',defaults],['initial_json',defaults]])html=html.replace('#{'+key+'}',()=>JSON.stringify(JSON.stringify(data)).replace(/</g,'\\u003c'));
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try {
  const page=await browser.newPage({viewport:{width:560,height:680}});const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.route('http://vgd-upgrade.test/',route=>route.fulfill({body:html,contentType:'text/html'}));
  await page.addInitScript(()=>{window.calls=[];window.sketchup=new Proxy({},{get:(_,key)=>data=>calls.push({action:key,data})});});
  await page.goto('http://vgd-upgrade.test/');
  await page.locator('[data-page="doors"]').click();
  await page.selectOption('#door_style','Shaker');
  await page.locator('[data-subtab="division"]').click();
  await page.getByRole('button',{name:'Dọc',exact:true}).click();
  await page.locator('#frame_sections').fill('3');await page.locator('#frame_bar_width').fill('30');
  let payload=await page.evaluate(()=>getFormData());
  if(payload.door_style!=='Shaker'||payload.frame_division!=='Dọc'||payload.frame_sections!==3||payload.frame_bar_width!==30||payload.pano_panel_count!==1)throw Error('Shaker/frame payload lost');
  await page.screenshot({path:'cabinet_dev/ui_frame_division.png'});
  await page.getByRole('button',{name:'Chéo X',exact:true}).click();
  if(await page.locator('#frame_sections').isVisible())throw Error('X section count visible');
  await page.locator('[data-subtab="pano"]').click();
  if(!await page.locator('#shaker_recess').isVisible())throw Error('Shaker recess hidden');
  await page.locator('#shaker_recess').fill('8');
  await page.screenshot({path:'cabinet_dev/ui_shaker.png'});
  await page.evaluate(p=>updateFormFromRuby({...p,__target_pid:'42',__model_guid:'model-42'}),defaults);
  await page.waitForTimeout(500);await page.locator('[data-page="library"]').click();
  if(await page.locator('#btn_library_save').isDisabled()||!await page.locator('#btn_library_replace').isDisabled())throw Error('Library selected cabinet state');
  await page.evaluate(()=>{calls=[];document.getElementById('live_update').checked=true;});
  await page.locator('#library_name').fill('Mẫu <img src=x onerror="window.injected=1">');
  await page.locator('#library_search').fill('phòng');await page.locator('#library_search').press('Enter');
  await page.waitForTimeout(700);
  if(await page.evaluate(()=>calls.some(c=>['update_cabinet','save_preset','create_cabinet'].includes(c.action))))throw Error('Library typing triggered modeling');
  payload=await page.evaluate(()=>getFormData());
  if('library_name' in payload||'library_search' in payload)throw Error('Library controls in cabinet params');
  await page.locator('#btn_library_save').click();let call=await page.evaluate(()=>calls.at(-1));
  if(call.action!=='save_library'||call.data.replace!==false||call.data.__target_pid!=='42'||call.data.__model_guid!=='model-42')throw Error('Library save target');
  const items=[{name:'Tủ phòng ngủ',dimensions:[1600,600,2400],version:'4.5.0-beta.1'},{name:'<img src=x onerror="window.injected=1">',dimensions:[800,600,2400],version:'4.5.0-beta.1'}];
  await page.evaluate(items=>receiveLibrary(items),items);
  if(await page.locator('.library-item').count()!==1)throw Error('Library search filter');
  await page.locator('#library_search').fill('');
  await page.locator('.library-item').first().click();
  call=await page.evaluate(()=>calls.at(-1));if(call.action!=='library_preview'||call.data!=='Tủ phòng ngủ')throw Error('Library preview route');
  await page.evaluate(()=>receiveLibraryPreview('other','data:image/png;base64,xxx'));
  if(await page.locator('#library_thumbnail').isVisible())throw Error('Late thumbnail not ignored');
  await page.evaluate(()=>receiveLibraryPreview('Tủ phòng ngủ','data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII='));
  if(!await page.locator('#library_thumbnail').isVisible()||await page.evaluate(()=>window.injected)||await page.locator('#library_list img').count())throw Error('Library thumbnail/text safety');
  await page.locator('#btn_library_replace').click();call=await page.evaluate(()=>calls.at(-1));
  if(call.action!=='save_library'||call.data.replace!==true||call.data.name!=='Tủ phòng ngủ')throw Error('Explicit replacement');
  await page.locator('#library_name').fill('Tủ mới');await page.getByRole('button',{name:'Đổi tên theo ô nhập',exact:true}).click();
  call=await page.evaluate(()=>calls.at(-1));if(call.action!=='rename_library'||call.data.source_name!=='Tủ phòng ngủ'||call.data.name!=='Tủ mới')throw Error('Library rename');
  await page.getByRole('button',{name:'Đặt tủ từ Thư viện',exact:true}).click();call=await page.evaluate(()=>calls.at(-1));
  if(call.action!=='place_library'||call.data!=='Tủ phòng ngủ')throw Error('Library placement');
  await page.evaluate(()=>{receiveLibrary([{name:'Tủ phòng ngủ',dimensions:[1600,600,2400],version:'4.5.0-beta.1'},{name:'Tủ bếp dưới',dimensions:[800,600,820],version:'4.5.0-beta.1'}]);document.getElementById('settings_content').scrollTop=0;});
  await page.screenshot({path:'cabinet_dev/ui_library.png'});
  await page.getByRole('button',{name:'Xóa khỏi danh sách',exact:true}).click();call=await page.evaluate(()=>calls.at(-1));
  if(call.action!=='delete_library'||call.data!=='Tủ phòng ngủ')throw Error('Library deletion');
  await page.evaluate(()=>{setSelectedCabinet(null);receiveLibrary([]);});
  if(!await page.locator('#btn_library_save').isDisabled()||!await page.locator('#btn_library_replace').isDisabled()||await page.locator('#library_detail').isVisible())throw Error('Cleared selection state');
  await page.setViewportSize({width:480,height:420});await page.screenshot({path:'cabinet_dev/ui_library_small.png'});
  if(await page.evaluate(()=>document.body.scrollWidth>innerWidth))throw Error('Library horizontal overflow');
  if(errors.length)throw Error(errors.join('\n'));
  console.log('PASS Edge upgrade UI: Shaker/division settings, library CRUD targets, search/text safety, late thumbnails, empty/selection states and typing isolated from live modeling');
 } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
