const fs=require('fs');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{
const defaults=JSON.parse(fs.readFileSync('cabinet_dev/defaults.json'));
const presets=JSON.parse(fs.readFileSync('cabinet_dev/presets.json'));
let html=fs.readFileSync('cabinet_work/VGD_Cabinet/VGD_Cabinet_UI.html','utf8');
if(!html.includes('<title>VGD Cabinet 4.5.0-beta.5</title>')||!html.includes('class=\"brand-version\">4.5.0 · Beta 5</small>'))throw Error('Cabinet UI version labels must match beta.5');
for(const [key,data] of [['presets_json',presets],['default_json',defaults],['initial_json',defaults]])html=html.replace('#{'+key+'}',()=>JSON.stringify(JSON.stringify(data)).replace(/</g,'\\u003c'));
fs.writeFileSync('cabinet_dev/preview.html',html);
const browser=await chromium.launch({headless:true,...(process.env.VGD_BROWSER_PATH ? {executablePath:process.env.VGD_BROWSER_PATH} : {channel:'msedge'})});
try {
const page=await browser.newPage({viewport:{width:560,height:640}});
let errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://vgd.test/',r=>r.fulfill({body:html,contentType:'text/html'}));
await page.addInitScript(()=>{window.calls=[];window.sketchup=new Proxy({},{get:(_,k)=>(data)=>calls.push({action:k,data})});});
await page.goto('http://vgd.test/');
await page.waitForTimeout(650);
if(!await page.locator('body').evaluate(e=>e.classList.contains('dark'))||await page.locator('html').evaluate(e=>e.style.colorScheme)!=='dark')throw Error('First launch is not dark');
await page.locator('#btn_theme').click();
if(await page.locator('body').evaluate(e=>e.classList.contains('dark'))||await page.evaluate(()=>localStorage.getItem('vgd_cabinet_theme'))!=='light')throw Error('Light theme did not persist to Cabinet preference');
await page.evaluate(()=>{localStorage.removeItem('vgd_cabinet_theme');localStorage.setItem('vgd_theme','light');});
await page.reload();await page.waitForTimeout(400);
if(await page.locator('body').evaluate(e=>e.classList.contains('dark'))||await page.evaluate(()=>localStorage.getItem('vgd_cabinet_theme'))!=='light')throw Error('Legacy light preference migration');
await page.screenshot({path:'cabinet_dev/ui_theme_light.png'});
await page.locator('#btn_theme').click();
if(!await page.locator('body').evaluate(e=>e.classList.contains('dark'))||await page.evaluate(()=>localStorage.getItem('vgd_cabinet_theme'))!=='dark')throw Error('Dark theme did not persist to Cabinet preference');
await page.screenshot({path:'cabinet_dev/ui_theme_dark.png'});
await page.setViewportSize({width:660,height:640});
let compactNav=await page.evaluate(()=>({width:document.querySelector('.side-menu').getBoundingClientRect().width,copy:getComputedStyle(document.querySelector('.menu-copy')).display,allNamed:[...document.querySelectorAll('.menu-button')].every(b=>b.title&&b.getAttribute('aria-label')&&b.querySelector('svg'))}));
if(compactNav.width>62||compactNav.copy!=='none'||!compactNav.allNamed)throw Error('Compact navigation must show tooltipped icons only');
await page.screenshot({path:'cabinet_dev/ui_navigation_compact.png'});
await page.setViewportSize({width:760,height:640});
let wideNav=await page.evaluate(()=>({width:document.querySelector('.side-menu').getBoundingClientRect().width,copy:getComputedStyle(document.querySelector('.menu-copy')).display,description:getComputedStyle(document.querySelector('.menu-description')).display}));
if(wideNav.width<190||wideNav.copy==='none'||wideNav.description==='none')throw Error('Wide navigation must show icon, name and description');
await page.screenshot({path:'cabinet_dev/ui_navigation_wide.png'});
await page.setViewportSize({width:560,height:640});
if(!await page.locator('#btn_update').isDisabled())throw Error('Update enabled without selection');
await page.evaluate(()=>updateCabinet(true));
if(await page.evaluate(()=>calls.some(c=>c.action==='update_cabinet')))throw Error('Update without selection');
await page.evaluate(()=>placeCabinet());
let call=await page.evaluate(()=>calls.at(-1));
if(call.action!=='create_cabinet'||call.data.t!==17.5)throw Error('Create payload');
await page.evaluate(p=>updateFormFromRuby({...p,__target_pid:'42'}),defaults);
await page.waitForTimeout(600);
await page.locator('#w').fill('900');
await page.locator('#btn_update').click();
call=await page.evaluate(()=>calls.at(-1));
if(call.action!=='update_cabinet'||call.data.__target_pid!=='42'||call.data.w!==900)throw Error('Update target');
await page.evaluate(()=>setSelectedCabinet(null));
await page.selectOption('#preset_select',{label:'Tủ áo 3 module độc lập'});
call=await page.evaluate(()=>getFormData());
if(call.module_mode!=='Độc lập'||call.module_widths!=='800;800;800')throw Error('Preset module fields');
await page.evaluate(()=>{document.getElementById('drawer_count').value='1.5';document.getElementById('t').value='';});
call=await page.evaluate(()=>getFormData());
if(call.drawer_count!==1.5||call.t!==null)throw Error('Input silently coerced');
await page.evaluate(p=>updateFormFromRuby(p),defaults);
await page.locator('[data-page="doors"]').click();
await page.selectOption('#door_style','Kính khung kim loại');
await page.locator('#metal_frame_width').fill('37');
await page.selectOption('#metal_finish','Champagne');
await page.selectOption('#glass_finish','Trà');
const glassParams=await page.evaluate(()=>getFormData());
if(glassParams.metal_frame_width!==37||glassParams.glass_thickness!==5||glassParams.metal_finish!=='Champagne')throw Error('Concept settings lost');
await page.waitForTimeout(180);
await page.screenshot({path:'cabinet_dev/ui_metal_glass.png'});
await page.locator('[data-subgroup="doors"][data-subtab="front"]').click();
await page.selectOption('#door_style','Pano khung gỗ');
await page.locator('#pano_panel_count').fill('2');
await page.locator('#pano_stile_width').fill('70');
if(!await page.locator('#pano_mid_rail').isVisible())throw Error('Pano midrail hidden');
const pano=await page.evaluate(()=>getFormData());
if(pano.pano_panel_count!==2||pano.pano_stile_width!==70||pano.pano_groove_depth!==8)throw Error('Pano payload');
await page.screenshot({path:'cabinet_dev/ui_pano.png'});
await page.evaluate(p=>updateFormFromRuby(p),defaults);
for(const name of ['general','frame','compartments','doors','drawers']){
 await page.locator('[data-page="'+name+'"]').click();
 await page.waitForTimeout(180);
 await page.screenshot({path:'cabinet_dev/ui_'+name+'.png',fullPage:false});
}
await page.locator('[data-page="drawers"]').click();
await page.selectOption('#opt_drawer','Âm');
await page.selectOption('#drawer_columns','2');
await page.locator('[data-subgroup="drawers"][data-subtab="frame"]').click();
await page.locator('#drawer_frame_depth').fill('400');
await page.screenshot({path:'cabinet_dev/ui_drawers_active.png'});
await page.locator('#drawer_frame_stop_rail').uncheck();
if(await page.locator('#drawer_frame_stop_rail_h').isVisible())throw Error('Head rail controls visible when off');
await page.locator('#drawer_frame_stop_rail').check();
await page.locator('[data-subgroup="drawers"][data-subtab="box"]').click();
await page.selectOption('#drawer_bottom_mode','Phủ dưới');
if(await page.locator('#drawer_bottom_offset').isVisible())throw Error('Overlay bottom offset visible');
let structure=await page.evaluate(()=>getFormData());
if(structure.drawer_columns!==2||structure.drawer_frame_depth!==400||structure.drawer_bottom_mode!=='Phủ dưới')throw Error('Structure payload lost');
await page.selectOption('#drawer_bottom_mode','Âm hai bên');
await page.screenshot({path:'cabinet_dev/ui_drawer_box.png'});
await page.locator('[data-subgroup="drawers"][data-subtab="front"]').click();
await page.locator('#drawer_bevel').check();
await page.locator('#drawer_bevel_lip').fill('3');
let handles=await page.evaluate(()=>getFormData());
if(!handles.drawer_bevel||handles.front_bevel||handles.drawer_bevel_lip!==3)throw Error('Handles not separated');
await page.screenshot({path:'cabinet_dev/ui_drawer_handles.png'});
await page.locator('[data-page="general"]').click();
await page.locator('.preset-section details').evaluate(e=>e.open=true);
await page.locator('#preset_name').fill('VGD thử');
await page.getByRole('button',{name:'Tạo mới',exact:true}).click();
call=await page.evaluate(()=>calls.at(-1));
if(call.action!=='save_preset'||call.data.action!=='create'||await page.locator('#preset_name').inputValue()!=='VGD thử')throw Error('Preset save acknowledgement');
await page.getByRole('button',{name:'Đổi tên mẫu',exact:true}).click();
call=await page.evaluate(()=>calls.at(-1));
if(call.data.action!=='rename'||!call.data.source_name)throw Error('Preset rename source missing');
await page.screenshot({path:'cabinet_dev/ui_presets.png'});
const cases=JSON.parse(fs.readFileSync('outputs/description_cases.json'));
await page.evaluate(({packet,defaults})=>receiveDescriptionContract({example:packet,defaults,enums:{}}),{packet:cases[0].packet,defaults});
await page.locator('[data-page="description"]').click();
await page.getByRole('button',{name:'Hướng dẫn cho ChatGPT',exact:true}).click();
if(!(await page.locator('#description_prompt').inputValue()).includes('MẪU:'))throw Error('Description prompt missing');
await page.locator('#description_prompt_box').evaluate(e=>e.open=false);
await page.getByRole('button',{name:'Nạp ví dụ',exact:true}).click();
const previousCalls=await page.evaluate(()=>calls.length);
await page.locator('#btn_description_check').click();
call=await page.evaluate(()=>calls.at(-1));
if(call.action!=='preview_description')throw Error('Description preview route');
const request=call.data.request_id;
await page.evaluate(({id,result})=>receiveDescriptionPreview(id,result),{id:request,result:cases[0].result});
if(await page.locator('#btn_description_apply').isDisabled())throw Error('Validated import not enabled');
await page.screenshot({path:'cabinet_dev/ui_description.png'});
await page.locator('#btn_description_apply').click();
call=await page.evaluate(()=>calls.at(-1));
if(call.action!=='apply_description')throw Error('Description apply route');
await page.evaluate(p=>applyDescriptionDraft(p),cases[0].result.parameters);
if(!await page.locator('#btn_update').isDisabled()||await page.locator('#live_update').isChecked())throw Error('Draft isolation');
await page.locator('#btn_place').click();call=await page.evaluate(()=>calls.at(-1));
if(call.action!=='create_cabinet'||call.data.__target_pid!==null||call.data.w!==800)throw Error('Imported placement');
await page.waitForTimeout(1100);
if(await page.evaluate(n=>calls.slice(n).some(c=>c.action==='update_cabinet'||c.action==='save_preset'),previousCalls))throw Error('Import mutated selected cabinet/preset');
await page.locator('[data-page="description"]').click();
await page.locator('#description_text').fill('invalid edited content');
if(!await page.locator('#btn_description_apply').isDisabled())throw Error('Edited import still approved');
const partialCase=cases.at(-1);
await page.locator('#description_text').fill(JSON.stringify(partialCase.packet));
await page.locator('#btn_description_check').click();
call=await page.evaluate(()=>calls.at(-1));const partialRequest=call.data.request_id;
await page.evaluate(({id,result})=>receiveDescriptionPreview(id,result),{id:partialRequest,result:partialCase.result});
if(!await page.locator('#btn_description_apply').isDisabled()||!await page.locator('#btn_description_partial').isVisible())throw Error('Partial button flags');
await page.locator('#btn_description_partial').scrollIntoViewIfNeeded();
await page.screenshot({path:'cabinet_dev/ui_description_partial.png'});
const cancelledCalls=await page.evaluate(()=>calls.length);
const cancelDialog=page.waitForEvent('dialog');
const cancelClick=page.locator('#btn_description_partial').click();
const cancel=await cancelDialog;
if(!cancel.message().includes('2200')||!cancel.message().includes('KHÔNG tự trừ')||!cancel.message().includes(partialCase.packet.unsupported_features[3]))throw Error('Partial confirmation missing scope');
await cancel.dismiss();await cancelClick;
if(await page.evaluate(()=>calls.length)!==cancelledCalls)throw Error('Cancel imported partial');
const acceptDialog=page.waitForEvent('dialog');
const acceptClick=page.locator('#btn_description_partial').click();
const accept=await acceptDialog;await accept.accept();await acceptClick;
call=await page.evaluate(()=>calls.at(-1));
if(call.action!=='apply_description'||call.data.allow_partial!==true||JSON.stringify(call.data.acknowledged_features)!==JSON.stringify(partialCase.packet.unsupported_features))throw Error('Partial acknowledgment payload');
await page.evaluate(r=>applyDescriptionDraft(r.parameters,r.unsupported_features),partialCase.result);
if(!await page.locator('#description_draft_notice').isVisible())throw Error('Partial draft notice missing');
await page.screenshot({path:'cabinet_dev/ui_description_partial_draft.png'});
await page.locator('#btn_place').click();call=await page.evaluate(()=>calls.at(-1));
if(call.action!=='create_cabinet'||call.data.w!==2200||call.data.h_top!==580||call.data.__target_pid!==null)throw Error('Partial placement mismatch');
await page.locator('[data-page="description"]').click();
console.log('PASS description Edge: exact user JSON, partial confirm/cancel dialogs, exact acknowledgment payload, persistent draft notice, 2200 mm placement, target isolation');
for(const viewport of [{width:560,height:640},{width:480,height:420}]){
 await page.setViewportSize(viewport);
 await page.evaluate(()=>{document.querySelectorAll('details').forEach(e=>e.open=true);document.getElementById('settings_content').scrollTop=9999;});
 const layout=await page.evaluate(()=>{const f=document.querySelector('footer').getBoundingClientRect();return {bottom:f.bottom,bodyWidth:document.body.scrollWidth,innerWidth:innerWidth,innerHeight:innerHeight,actions:[...document.querySelectorAll('.action-bar button')].every(b=>{const r=b.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight&&r.left>=0&&r.right<=innerWidth;})}});
 if(layout.bottom>layout.innerHeight||layout.bodyWidth>layout.innerWidth||!layout.actions)throw Error('Footer clipped or horizontal overflow: '+JSON.stringify(layout));
}
await page.screenshot({path:'cabinet_dev/ui_small.png'});
if(errors.length)throw Error(errors.join('\n'));
const duplicate=await page.evaluate(()=>{let ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.length-new Set(ids).size;});
if(duplicate)throw Error('Duplicate IDs');
console.log('PASS UI: load, create, update target, no selection, presets, invalid numeric preservation, no JS errors, no duplicate IDs');
} finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1});
